# Generated by Django 6.0.6 on 2026-06-14 10:34

import django.db.models.deletion
import filetransfer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='filetransfe_user_id_80198c_idx'), models.Index(fields=['action'], name='filetransfe_action_644fa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='encrypted_files/%Y/%m/%d/')),
                ('encrypted_aes_key', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('file_hash', models.CharField(max_length=64)),
                ('aes_nonce', models.BinaryField()),
                ('aes_tag', models.BinaryField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DOWNLOADED', 'Downloaded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=filetransfer.models.default_expiry)),
                ('download_limit', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('encryption_time_ms', models.PositiveIntegerField(default=0)),
                ('decryption_time_ms', models.PositiveIntegerField(default=0)),
                ('kyber_time_ms', models.PositiveIntegerField(default=0)),
                ('dilithium_time_ms', models.PositiveIntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'created_at'], name='filetransfe_sender__8340d0_idx'), models.Index(fields=['receiver', 'status'], name='filetransfe_receive_7fac32_idx'), models.Index(fields=['status', 'expires_at'], name='filetransfe_status_40b91b_idx')],
            },
        ),
    ]
